refactor(config/dotsetup): moved to new req

diff --git a/config/dotsetup b/config/dotsetup
--- a/config/dotsetup
+++ b/config/dotsetup
@@ -1,140 +1,149 @@
 #!/usr/bin/env zsh
 
-local help verbose use_default use_all dry custom delete
+local help verbose_flag default_flag all_flag dry_flag delete_flag custom 
 
+local name="${0:t}"
 local usage=(
     'Usage:'
-    '  dotsetup [-h|--help] [-v|--verbose]'
-    '  dotsetup [-d|--default] [-a|--all]  [--uninstall]'
-    '  dotsetup [-n|--dry-run] [-c|--custom]'
-    '\nDefault list can be extended using exported ${DOTSETUP_DEFAULT} w/ <space> delimiter'
+    "\t$name [-h|--help]"
+    "\t$name [--uninstall]"
+    "\t$name [-a|--all]"
+    "\t$name [-n|--dry-run]"
+    "\t$name [-v|--verbose]"
+    "\t$name [-d|--default]"
+    "\t$name [-c|--custom] <name_of_relative_module>"
 )
 
-local deps_list=(
+local deps=(
     'stow'
     'git'
 )
 
-zparseopts -D -F \
+zparseopts -D -F -- \
     {h,-help}=help \
-    {v,-verbose}=verbose \
-    {d,-default}=use_default \
-    {n,-dry-run}=dry \
-    -uninstall=delete \
+    {v,-verbose}=verbose_flag \
+    {a,-all}=all_flag \
+    {d,-default}=default_flag \
     {c,-custom}+:=custom \
-    {a,-all}=use_all ||
+    {n,-dry-run}=dry_flag \
+    -uninstall=delete_flag ||
     { print -l "\n${(@)usage}" && exit 1 }
 
-local self_location="$(realpath $0 | xargs dirname)"
+[[ -z $help ]] || { print -l "${(@)usage}" && exit 0 }
 
 function parse_argv() {
-    [[ -z $help ]] || { print -l "${(@)usage}" && exit 0 }
-
-	[[ -z $use_all ]] || {
-        unset use_default
-        custom=()
-
-        for item in "$self_location"/*; do
-            [[ -d $item ]] || continue
-
-            custom+=("$(basename $item)")
-        done
-
-        return
-    }
-
     [[ -z $custom ]] || {
-        local temp_arr=()
-
+        local temp=()
         for i in {2..$#custom..2}; do
-            temp_arr+=("${custom[$i]}")
+            temp+=("${custom[$i]}")
         done
 
-        unset custom
-        custom=("${(@)temp_arr}")
-
-        unset temp_arr
-	}
+        custom=("${(@)temp}")
+    }
 }
 
 function check_deps() {
-    local failed
+    [[ -n $deps ]] || { echo '[!] Incorrect env - check_deps' && exit 2 }
 
-    for dep in "${(@)deps_list}"; do
-        type "$dep" &>/dev/null || { echo "[!] No $dep installed" && failed=1 }
+    local failed
+    for dep in "${(@)deps}"; do
+        type "$dep" &>/dev/null || { echo '[!] Missing -' "$dep" && failed=1 }
     done
 
     [[ -z $failed ]] || { exit 1 }
 }
 
-function check_dir() {
-    local target="$1"
-    [[ -n $target ]] || { echo '[!] check_dir :: no dir' && exit 2 }
+function check_module() {
+    local module="$1"
+    [[ -n $module ]] || { echo '[!] Incorrect usage - check_module' && exit 2 }
 
-    [[ -e $target ]] || { echo '[!] check_dir :: dir do not exist' "\n$target" && exit 2 }
-    [[ -d $target ]] || { echo '[!] check_dir :: not a dir' "\n$target" && exit 2 }
+    [[ -e $module ]] || { echo '[!] Dirictory does not exist -' "$module" && exit 1 }
+    [[ -d $module ]] || { echo '[!] File is not a directory -' "$module" && exit 1 }
 }
 
-function deploy() {
-    local target="${self_location}/$1"
-    [[ -n $target ]] || { echo '[!] deploy :: no target' && exit 2 }
+function deploy_module() {
+    local location="$1"
+    local module_name="$2"
+    [[ -n $location && -n $module_name ]] || { echo '[!] Incorrect usage - deploy_module' && exit 2 }
 
-    check_dir "$target"
+    local module="$location/$module_name"
+    check_module "$module"
 
     local args=(
-        '-R'  # restow
+        # restow
+        '-R'
     )
 
-    [[ -z $dry ]] || { args+=('--simulate') }
-    [[ -z $delete ]] || { args+=('--delete') }
+    [[ -z $dry_flag ]] || { args+=('--simulate') }
+    [[ -z $delete_flag ]] || { args+=('--delete') }
 
     local packages=()
 
-    for package in "$target"/*; do
+    for package in "$module"/*; do
         packages+=("$(basename $package)")
     done
 
-    [[ -z $verbose ]] || {
+    [[ -z $verbose_flag ]] || {
         args+=('-v')
 
-        echo '[?] Found following packages in the dir:'
+        echo '[?] Packages in the module:'
 
-        for idx in {1.."${#packages}"}; do
+        for idx in {1..$#packages}; do
             echo "$idx." "${packages[$idx]}"
         done
 
-        echo '\n[?] Press <Enter> to continue'
+        echo '\n<Enter> to continue'
         read
 	}
 
     stow \
         "${(@)args}" \
         -t "$HOME" \
-        -d "$target" \
+        -d "$module" \
         "${(@)packages}"
 
-    return "$?"
+    return $?
+}
+
+function get_all_modules() {
+    local exec_basedir="$1"
+    [[ -n $exec_basedir ]] || { echo '[!] Incorrect usage - get_all_modules' && exit 2 }
+
+    local res=()
+    for module in "$exec_basedir"/*; do
+        [[ -d $module ]] || continue
+        res+=("$(basename $module)")
+    done
+
+    echo "${(@)res}"
 }
 
 function main() {
+    local exec_basedir="$1"
+    [[ -n $exec_basedir ]] || { echo '[!] Incorrect usage - main' && exit 2 }
+
     check_deps
+    parse_argv
 
-    local dir_list=()
+    local modules=()
+    typeset -U modules
 
-    [[ -n $use_all && -z $use_default ]] || { dir_list+=('default') }
+    [[ -n $all_flag ]] && {
+        modules=($(get_all_modules "$exec_basedir"))
+    } || {
+        [[ -z $use_default ]] || { modules+=('default') }
+        [[ -z $custom ]] || { modules+=(${(@)custom}) }
+    }
 
-    [[ -z $custom ]] || { dir_list+=("${(@)custom}") }
-
-    for dir in "${(@)dir_list}"; do
-        [[ -z $verbose ]] || {
-            echo '\n[?] stow on dir' "$dir"
-            echo '[?] Press <Enter> to continue'
+    for module in "${(@)modules}"; do
+        [[ -z $verbose_flag ]] || {
+            echo '\n[?] Deploy module -' "$module"
+            echo '<Enter> to continue'
             read
         }
 
-        deploy "$dir"
+        deploy_module "$exec_basedir" "$module"
     done
 }
 
-parse_argv
-main
+main "$(dirname $(realpath $0))"
