refactor(local-bin): moved to new req

diff --git a/config/default/local-bin/.local/bin/adbinstall b/config/default/local-bin/.local/bin/adbinstall
--- a/config/default/local-bin/.local/bin/adbinstall
+++ b/config/default/local-bin/.local/bin/adbinstall
@@ -2,12 +2,13 @@
 
 local help
 
+local name="${0:t}"
 local usage=(
     'Usage:'
-    '\tadbinstall [-h|--help]'
+    "\t$name [-h|--help]"
 )
 
-local deps_list=(
+local deps=(
     'adb'
     'fd'
     'fzf'
@@ -15,29 +16,30 @@ local deps_list=(
 
 zparseopts -D -F -- \
     {h,-help}=help ||
-    { print -l "${(@)usage}" && exit 1 }
+    { print -l "\n${(@)usage}" && exit 1 }
 
 [[ -z $help ]] || { print -l "${(@)usage}" && exit 0 }
 
 function check_deps() {
-    local failed
+    [[ -n $deps ]] || { echo '[!] Incorrect env - check_deps' && exit 2 }
 
-    for dep in "${(@)deps_list}"; do
-        type "$dep" &>/dev/null || { echo "[!] No $dep installed" && failed=1 }
+    local failed
+    for dep in "${(@)deps}"; do
+        type "$dep" &>/dev/null || { echo '[!] Missing -' "$dep" && failed=1 }
     done
 
-    [[ -z $failed ]] || { exit 2 }
+    [[ -z $failed ]] || { exit 1 }
 }
 
 function main() {
     check_deps
 
-    fd -t f -e apk -IH --max-depth 10 |
+    fd -t f -e apk -IH --max-depth 10 | \
     fzf \
         --multi \
         --preview 'stat -c %Y {} | xargs -I {} date -d @{}' \
         --preview-window "right:$(( $(tput cols) / 4 * 3 )):border-vertical" \
-        --bind "ctrl-\\:change-preview-window($(( $(tput cols) / 5 ))|$(( $(tput cols) / 4 * 3 )))" |
+        --bind "ctrl-\\:change-preview-window($(( $(tput cols) / 5 ))|$(( $(tput cols) / 4 * 3 )))" | \
     xargs -I {} adb install -d -r {}
 }
 
diff --git a/config/default/local-bin/.local/bin/clipboard2webp b/config/default/local-bin/.local/bin/clipboard2webp
--- a/config/default/local-bin/.local/bin/clipboard2webp
+++ b/config/default/local-bin/.local/bin/clipboard2webp
@@ -1,25 +1,27 @@
 #!/usr/bin/env zsh
 
-local help temp res
+local help
 
+local name="${0:t}"
 local usage=(
     'Optimizes image in clipboard and converts to webp\n'
     'Usage:'
-    '\tclipboard2webp [-h|--help]'
+    "\t$name [-h|--help]"
 )
 
-local depsList=(
+local deps=(
     'ffmpeg'
 )
 
-zparseopts -D -F \
+zparseopts -D -F -- \
     {h,-help}=help ||
-    { printf -l "${(@)usage}" && exit 1 }
+    { printf -l "\n${(@)usage}" && exit 1 }
 
 [[ -z $help ]] || { print -l "${(@)usage}" && exit 0 }
 
-function readClipboardToFile() {
+function read_clipboard_to_file() {
     local file="$1"
+    [[ -n $file ]] || { echo '[!] Incorrect usage - read_clipboard_to_file' && exit 2 }
     [[ -f $file ]] || { echo '[!] No target file found' && exit 2 }
 
     osascript \
@@ -32,40 +34,40 @@ function readClipboardToFile() {
 function convert() {
     local input="$1"
     local target="$2"
-    [[ -n $input && -n $target ]] || { echo '[!] No input or target provided' && exit 2 }
+    [[ -n $input && -n $target ]] || { echo '[!] Incorrect usage - convert' && exit 2 }
 
     ffmpeg -i "$input" "$target"
 }
 
-function writeImageToClipboard() {
+function write_image_to_clipboard() {
     local image="$1"
+    [[ -n $image ]] || { echo '[!] Incorrect usage - write_image_to_clipboard' && exit 2 }
     [[ -f $image ]] || { echo '[!] No image found' && exit 2 }
 
     osascript -e "set the clipboard to (read (POSIX file \"$image\") as «class PNGf»)"
 }
 
-function checkDeps() {
-    [[ ${#@} != 0 ]] || { echo '[!] No deps passed' && exit 2 }
+function check_deps() {
+    [[ -n $deps ]] || { echo '[!] Incorrect env - check_deps' && exit 2 }
 
     local failed
-
-    for dep in "$@"; do
-        type "$dep" &>/dev/null || { echo "[!] No $dep found" && failed=1 }
+    for dep in "${(@)deps}"; do
+        type "$dep" &>/dev/null || { echo '[!] Missing -' "$dep" && failed=1 }
     done
 
     [[ -z $failed ]] || { exit 1 }
 }
 
 function main() {
-    checkDeps "${(@)depsList}"
+    check_deps
 
-    temp="$(mktemp -t clipboard.XXXXXXXXXX)"
-    res="$temp.webp"
+    local temp="$(mktemp -t clipboard.XXXXXXXXXX)"
+    local res="$temp.webp"
     trap '(unlink "$temp"; unlink "$res") &>/dev/null' EXIT INT
 
-    readClipboardToFile "$temp" || { echo '[!] Can not convert to image type' && exit 1 }
+    read_clipboard_to_file "$temp" || { echo '[!] Can not convert to image type' && exit 1 }
     convert "$temp" "$res" || { echo '[!] Convertion to webp failed' && exit 1 }
-    writeImageToClipboard "$res"
+    write_image_to_clipboard "$res"
 }
 
 main
diff --git a/config/default/local-bin/.local/bin/nice_ b/config/default/local-bin/.local/bin/nice_
--- a/config/default/local-bin/.local/bin/nice_
+++ b/config/default/local-bin/.local/bin/nice_
@@ -2,27 +2,31 @@
 
 local help
 
+local name="${0:t}"
 local usage=(
     'Usage:'
-    '\tnice_ [-h|-help]'
-    '\n\tUses $NICE_EXT of kv pair with : as separator to execute stuff'
+    "\t$name [-h|-help]"
+    '\nUses $NICE_EXT of kv pair with : as separator to execute stuff'
 )
 
-local dependencies=(
+local deps=(
     'procs'
 )
 
 zparseopts -D -F -- \
     {h,-help}=help ||
-    { print -l "${(@)usage}" && exit 1 }
+    { print -l "\n${(@)usage}" && exit 1 }
 
 [[ -z $help ]] || { print -l "${(@)usage}" && exit 0 }
 
-function check_deps() {
-    local failed
+local nice_arr
 
-    for dep in "${(@)dependencies}"; do
-        type "$dep" &>/dev/null || { failed=1; echo "[!] No dependency - $dep" }
+function check_deps() {
+    [[ -n $deps ]] || { echo '[!] Incorrect env - check_deps' && exit 2 }
+
+    local failed
+    for dep in "${(@)deps}"; do
+        type "$dep" &>/dev/null || { echo '[!] Missing -' "$dep" && failed=1 }
     done
 
     [[ -z $failed ]] || { exit 1 }
@@ -50,7 +54,7 @@ function get_extensions() {
     unset ext_arr
 }
 
-function main() {
+function process() {
     for key val in "${(@kv)nice_arr}"; do
         (( $key >= 0 )) && { priority="+${key}" } || { priority="$key" }
 
@@ -72,7 +76,12 @@ function main() {
     wait
 }
 
-check_deps
-declare -A nice_arr
-get_extensions
+function main() {
+    check_deps
+    declare -A nice_arr
+    get_extensions
+    process
+
+}
+
 main
diff --git a/config/default/skhd-bin/.local/bin/skhd/inputmute b/config/default/skhd-bin/.local/bin/skhd/inputmute
--- a/config/default/skhd-bin/.local/bin/skhd/inputmute
+++ b/config/default/skhd-bin/.local/bin/skhd/inputmute
@@ -1,15 +1,16 @@
 #!/usr/bin/env zsh
 
-local deps_list=(
+local deps=(
     'SwitchAudioSource'
     'terminal-notifier'
 )
 
 function check_deps() {
-    local failed
+    [[ -n $deps ]] || { echo '[!] Incorrect usage - check_deps' && exit 2 }
 
-    for dep in "${(@)deps_list}"; do
-        type "$dep" &>/dev/null || { echo "[!] No $dep installed" && failed=1 }
+    local failed
+    for dep in "${(@)deps}"; do
+        type "$dep" &>/dev/null || { echo '[!] Missing -' "$dep" && failed=1 }
     done
 
     [[ -z $failed ]] || { exit 1 }
