style: moved to 4 space tabulation
also moved from spaces in usages and descriptions to tabs

diff --git a/config/default/local-bin/.local/bin/adbinstall b/config/default/local-bin/.local/bin/adbinstall
--- a/config/default/local-bin/.local/bin/adbinstall
+++ b/config/default/local-bin/.local/bin/adbinstall
@@ -3,44 +3,44 @@
 local help
 
 local usage=(
-	'Usage:'
-	'	adbinstall [-h|--help]'
+    'Usage:'
+    '\tadbinstall [-h|--help]'
 )
 
 local deps_list=(
-	'adb'
-	'fd'
-	'fzf'
+    'adb'
+    'fd'
+    'fzf'
 )
 
 zparseopts -D -F -- \
-	{h,-help}=help ||
-	{ print -l "${usage[@]}" && exit 1 }
+    {h,-help}=help ||
+    { print -l "${usage[@]}" && exit 1 }
 
 [[ -z $help ]] || { print -l "${usage[@]}" && exit 0 }
 
 function check_deps() {
-	[[ ${#@} != 0 ]] || { echo '[!] check_deps :: none passed' && exit 2 }
+    [[ ${#@} != 0 ]] || { echo '[!] check_deps :: none passed' && exit 2 }
 
-	local failed
+    local failed
 
-	for dep in "$@"; do
-		type "$dep" &>/dev/null || { echo "[!] No $dep installed" && failed=1 }
-	done
+    for dep in "$@"; do
+        type "$dep" &>/dev/null || { echo "[!] No $dep installed" && failed=1 }
+    done
 
-	[[ -z $failed ]] || { exit 2 }
+    [[ -z $failed ]] || { exit 2 }
 }
 
 function main() {
-	check_deps "${deps_list[@]}"
+    check_deps "${deps_list[@]}"
 
-	fd -t f -e apk -IH --max-depth 10 |
-	fzf \
-		--multi \
-		--preview 'stat -c %Y {} | xargs -I {} date -d @{}' \
-		--preview-window "right:$(( $(tput cols) / 4 * 3 )):border-vertical" \
-		--bind "ctrl-\\:change-preview-window($(( $(tput cols) / 5 ))|$(( $(tput cols) / 4 * 3 )))" |
-	xargs -I {} adb install -d -r {}
+    fd -t f -e apk -IH --max-depth 10 |
+    fzf \
+        --multi \
+        --preview 'stat -c %Y {} | xargs -I {} date -d @{}' \
+        --preview-window "right:$(( $(tput cols) / 4 * 3 )):border-vertical" \
+        --bind "ctrl-\\:change-preview-window($(( $(tput cols) / 5 ))|$(( $(tput cols) / 4 * 3 )))" |
+    xargs -I {} adb install -d -r {}
 }
 
 main
diff --git a/config/default/local-bin/.local/bin/agi b/config/default/local-bin/.local/bin/agi
--- a/config/default/local-bin/.local/bin/agi
+++ b/config/default/local-bin/.local/bin/agi
@@ -3,20 +3,20 @@
 local help query
 
 local usage=(
-	'The silver searcher  wrapped in fzf\n'
-	'Usage:'
-	'\tagi [-h|--help]'
-	'\tagi <value-to-be-searched>'
+    'The silver searcher  wrapped in fzf\n'
+    'Usage:'
+    '\tagi [-h|--help]'
+    '\tagi <value-to-be-searched>'
 )
 
 local deps=(
-	'fzf'
-	'ag'
+    'fzf'
+    'ag'
 )
 
 zparseopts -D -F -- \
-	{h,-help}=help ||
-	{ print -l "${usage[@]}" && exit 1 }
+    {h,-help}=help ||
+    { print -l "${(@)usage}" && exit 1 }
 
 [[ -z $help ]] || { print -l "${usage[@]}" && exit 0 }
 [[ -n $@ ]] && { query="$@" } || { print -l '[!] No search query passed' "${usage[@]}" && exit 1 }
@@ -27,10 +27,10 @@ local preview_width_folded="$(( $width / 5 ))"
 
 local fzf_preview=$(cat <<'EOF'
 bat \
-	--style=numbers \
-	--color=always \
-	--highlight-line {2} \
-	{1}
+    --style=numbers \
+    --color=always \
+    --highlight-line {2} \
+    {1}
 EOF
 )
 
@@ -45,25 +45,25 @@ EOF
 )
 
 function main() {
-	ag --nobreak --noheading "$query" |
-	fzf \
-		--delimiter ':' \
-		--with-nth 1,2 \
-		--preview="${fzf_preview}" \
-		--preview-window="${fzf_preview_window}" \
-		--bind="${fzf_fold_bind}"
+    ag --nobreak --noheading "$query" |
+    fzf \
+        --delimiter ':' \
+        --with-nth 1,2 \
+        --preview="${fzf_preview}" \
+        --preview-window="${fzf_preview_window}" \
+        --bind="${fzf_fold_bind}"
 }
 
 function check_deps() {
-	[[ ${#@} != 0 ]] || { echo '[!] No dependencies has been passed to check_deps' && exit 2 }
+    [[ ${#@} != 0 ]] || { echo '[!] No dependencies has been passed to check_deps' && exit 2 }
 
-	local failed
+    local failed
 
-	for dep in "$@"; do
-		type "$dep" >&/dev/null || { echo "[!] No ${dep} installed" && failed=1 }
-	done
+    for dep in "$@"; do
+        type "$dep" >&/dev/null || { echo "[!] No ${dep} installed" && failed=1 }
+    done
 
-	[[ -z $failed ]] || { exit 2 }
+    [[ -z $failed ]] || { exit 2 }
 }
 
 check_deps "${deps[@]}"
diff --git a/config/default/skhd-bin/.local/bin/skhd/inputmute b/config/default/skhd-bin/.local/bin/skhd/inputmute
--- a/config/default/skhd-bin/.local/bin/skhd/inputmute
+++ b/config/default/skhd-bin/.local/bin/skhd/inputmute
@@ -1,37 +1,36 @@
 #!/usr/bin/env zsh
 
 local deps_list=(
-	'SwitchAudioSource'
-	'terminal-notifier'
+    'SwitchAudioSource'
+    'terminal-notifier'
 )
 
 local lock_file='/tmp/inputmute_lock'
 mkdir "$lock_file" 2>/dev/null || { exit 0 }
 
 function teardown() {
-	rmdir "$lock_file" 2>/dev/null
+    rmdir "$lock_file" 2>/dev/null
 }
 
 trap 'teardown' EXIT INT
 
 function check_deps() {
-	[[ ${#@} != 0 ]] || { echo '[!] check_deps :: none passed' && exit 2 }
+    [[ ${#@} != 0 ]] || { echo '[!] check_deps :: none passed' && exit 2 }
 
-	local failed
+    local failed
 
-	for dep in "$@"; do
-		type "$dep" &>/dev/null || { echo "[!] No $dep installed" && failed=1 }
-	done
+    for dep in "$@"; do
+        type "$dep" &>/dev/null || { echo "[!] No $dep installed" && failed=1 }
+    done
 
-	[[ -z $failed ]] || { exit 1 }
+    [[ -z $failed ]] || { exit 1 }
 }
 
 function main() {
-	check_deps "${deps_list[@]}"
+    check_deps "${deps_list[@]}"
 
-	terminal-notifier \
-		-title 'InputMute' \
-		-message "$(SwitchAudioSource -m toggle -t input)" 
+    terminal-notifier \
+        -title 'InputMute' \
 }
 
 main
